
const Homeproduct = [
    {
        id: 1,
        Name: 'Samsung Smart TV 47 Inch',
        price: "50000",
        Image: "image/p1.webp",
        cat: 'tv',
        type: 'new',
    },
    {
        id: 2,
        Name: "Dell Workstation T7910",
        price: "250000",
        Image: "image/P1.jpeg",
        cat: 'Workstation',
        type: 'featured',
    },
    {
        id: 3,
        Name: "Macbook Pro 15",
        price: "60000",
        Image: "image/p2.webp",
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 4,
        Name: "Msi Graphic Card M-2304",
        price: "210000",
        Image: "image/p2.jpeg",
        cat: 'Graphic Cards',
        type: 'top',
    },
    {
        id: 5,
        Name: "Lenovo P360 ThinkStation/8GB/",
        price: "85999",
        Image: "image/p3.jpeg",
        cat: 'Workstation',
        type: 'featured',
    },
    {
        id: 6,
        Name: "Nvidia Tesla Graphic Card",
        price: "60000",
        Image: "image/p4.jpeg",
        cat: 'Workstation',
        type: 'featured',
    },
    {
        id: 7,
        Name: "Nvidia H800 GPU NvLink",
        price: "600000",
        Image: "image/p5.jpeg",
        cat: "Servers",
        type: "new",
    },
    {
        id: 8,
        Name: "ThinkSystem Server AMD",
        Image: "image/p6.jpeg",
        price: "240000",
        cat: "Servers",
        type: "featured",
    },
    {
        id: 9,
        Name: "Apple Smart Watch",
        Image: "image/p3.webp",
        price: "10000",
        cat: "Watch",
        type: "new",
    },
    {
        id: 10,
        Name: "3M HeadPhones",
        Image: "image/p10.jpg",
        price: "7000",
        cat: "headphones",
        type: "featured",
    },
    {
        id: 11,
        Name: "JVC Speaker",
        Image: "image/p7.webp",
        price: "20000",
        cat: "Speakers",
        type: "top",
    },
    {
        id: 12,
        Name:"JBL Speaker",
        Image: "image/p8.webp",
        price: "15000",
        cat: "Speakers",
        type: "featured",
    },
    {
        id: 13,
        Name: "CCTV 360 Camera",
        Image: "image/p5.webp",
        cat:"Electronics",
        price: "3000",
        type: "new",
    },
    {
        id: 13,
        Name: "ASUS Motherboard",
        Image: "image/p14.jpeg",
        price: "210000",
        cat: "Motherboards",
        type: 'top',
    },
    {
        id: 14,
        Name: "DR MOS Motherboard",
        Image: "image/p15.jpeg",
        price: "133000",
        cat: "Motherboards",
        type: "top",
    },
    {
        id: 15,
        Name: "Nvidia Gaming X motherboard",
        price: "249900",
        Image: "image/p16.jpeg",
        cat: "Motherboards",
        type: "top",
    },

]

export default Homeproduct;